apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: asterism
resources:
  - ./base/deployment.yaml
  - ./base/service.yaml
images:
  - name: cluster
    newName: ghcr.io/jlfowle/asterism-cluster
    newTag: latest
labels:
  - pairs:
      app.kubernetes.io/name: cluster
      app.kubernetes.io/part-of: asterism
    includeSelectors: true
    includeTemplates: true
