apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pfsense-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: pfsense-secrets
    creationPolicy: Owner
  data:
    - secretKey: snmpHost
      remoteRef:
        key: /asterism/pfsense
        property: snmpHost
    - secretKey: snmpPort
      remoteRef:
        key: /asterism/pfsense
        property: snmpPort
    - secretKey: snmpCommunity
      remoteRef:
        key: /asterism/pfsense
        property: snmpCommunity
    - secretKey: consoleUrl
      remoteRef:
        key: /asterism/pfsense
        property: consoleUrl
    - secretKey: expectedUpInterfaces
      remoteRef:
        key: /asterism/pfsense
        property: expectedUpInterfaces
