apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pfsense
spec:
  to:
    kind: Service
    name: pfsense
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
