version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/services/polaris"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/services/unifi"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/services/cluster"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/services/pfsense"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/services/polaris"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/services/unifi"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/services/cluster"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/services/pfsense"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
