apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: asterism
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - externalsecret.yaml
images:
  - name: cluster
    newName: ghcr.io/jlfowle/asterism-cluster
    newTag: latest
commonLabels:
  app.kubernetes.io/name: cluster
  app.kubernetes.io/part-of: asterism
