apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cluster
spec:
  to:
    kind: Service
    name: cluster
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
