apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: unifi-secrets
    creationPolicy: Owner
  data:
    - secretKey: apiBaseUrl
      remoteRef:
        key: /asterism/unifi
        property: apiBaseUrl
    - secretKey: apiToken
      remoteRef:
        key: /asterism/unifi
        property: apiToken
    - secretKey: siteId
      remoteRef:
        key: /asterism/unifi
        property: siteId
    - secretKey: consoleUrl
      remoteRef:
        key: /asterism/unifi
        property: consoleUrl
