apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: asterism
resources:
  - ./base/deployment.yaml
  - ./base/service.yaml
  - ./base/route.yaml
  - ./base/externalsecret.yaml
images:
  - name: polaris
    newName: ghcr.io/jlfowle/asterism-polaris
    newTag: latest
commonLabels:
  app.kubernetes.io/name: polaris
  app.kubernetes.io/part-of: asterism
