apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: asterism
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - externalsecret.yaml
images:
  - name: polaris
    newName: ghcr.io/jlfowle/asterism-polaris
    newTag: latest
commonLabels:
  app.kubernetes.io/name: polaris
  app.kubernetes.io/part-of: asterism
