apiVersion: v1
kind: ServiceAccount
metadata:
  name: asterism-auth-proxy
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.public: https://asterism.apps.os.fowler.house/oauth/callback
automountServiceAccountToken: true
