apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: asterism-auth-proxy-cookie
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: asterism-auth-proxy-cookie
    creationPolicy: Owner
  data:
    - secretKey: cookie-secret
      remoteRef:
        key: /asterism/auth-proxy
        property: cookieSecret
