apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: polaris-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: polaris-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /asterism/polaris
