apiVersion: v1
kind: ConfigMap
metadata:
  name: polaris-runtime-config
data:
  runtime-config.json: |-
    {
      "edgeAuthEnabled": true,
      "modeLabel": "OpenShift SSO",
      "signOutPath": "/oauth/sign_out"
    }
