#!/usr/bin/env bash
#
# update-deploy.sh - Auto-discover deployable services and generate consolidated kustomization
#
# This script scans services/ for deployable services and generates deploy/kustomization.yaml
# that aggregates them with platform cross-cutting concerns.
#
# A service is considered "deployable" if it has:
#   1. services/{service}/Dockerfile
#   2. services/{service}/Makefile
#   3. services/{service}/deploy/kustomization.yaml
#
# Usage:
#   ./scripts/update-deploy.sh
#
# The script always exits with code 0. Discoveries are reported as informational output.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Discover deployable services
discover_services() {
    local services=()
    local services_dir="$REPO_ROOT/services"
    
    if [[ ! -d "$services_dir" ]]; then
        echo -e "${YELLOW}⚠ No services/ directory found${NC}"
        return 0
    fi
    
    for service_path in "$services_dir"/*; do
        if [[ ! -d "$service_path" ]]; then
            continue
        fi
        
        local service_name=$(basename "$service_path")
        
        # Check deployment criteria
        local has_dockerfile=false
        local has_makefile=false
        local has_kustomization=false
        
        [[ -f "$service_path/Dockerfile" ]] && has_dockerfile=true
        [[ -f "$service_path/Makefile" ]] && has_makefile=true
        [[ -f "$service_path/deploy/kustomization.yaml" ]] && has_kustomization=true
        
        # Service is deployable if it meets all three criteria
        if [[ "$has_dockerfile" == true && "$has_makefile" == true && "$has_kustomization" == true ]]; then
            services+=("$service_name")
        fi
    done
    
    # Sort services for consistent output
    if [[ ${#services[@]} -gt 0 ]]; then
        mapfile -t services < <(printf '%s\n' "${services[@]}" | sort)
        printf '%s\n' "${services[@]}"
    fi
}

# Generate kustomization.yaml content
generate_kustomization() {
    local services=("$@")
    
    cat << 'EOF'
# AUTO-GENERATED by scripts/update-deploy.sh
# Do not edit manually. Run: scripts/update-deploy.sh to regenerate
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
EOF
    
    # Add service references
    for service in "${services[@]}"; do
        echo "  - ../services/$service/deploy"
    done
    
    # Add platform cross-cutting concerns
    echo "  - platform/security"
}

# Main
main() {
    echo -e "${BLUE}Discovering deployable services...${NC}"
    
    # Discover services
    mapfile -t discovered_services < <(discover_services)
    
    if [[ ${#discovered_services[@]} -eq 0 ]]; then
        echo -e "${YELLOW}⚠ No deployable services found${NC}"
        discovered_services=()
    else
        echo -e "${GREEN}✓ Found ${#discovered_services[@]} deployable service(s):${NC}"
        for service in "${discovered_services[@]}"; do
            echo "  - $service"
        done
    fi
    
    # Generate kustomization
    echo ""
    echo -e "${BLUE}Generating deploy/kustomization.yaml...${NC}"
    local output_file="$REPO_ROOT/deploy/kustomization.yaml"
    generate_kustomization "${discovered_services[@]}" > "$output_file"
    
    echo -e "${GREEN}✓ Updated $output_file${NC}"
    echo ""
    
    # Validate the generated file
    if kustomize build "$REPO_ROOT/deploy" > /dev/null 2>&1; then
        echo -e "${GREEN}✓ Consolidated kustomization validates successfully${NC}"
    else
        echo -e "${YELLOW}⚠ Warning: Consolidated kustomization has validation issues${NC}"
        echo "  Run: kustomize build deploy/ for details"
    fi
}

main "$@"
