name: CI Pipeline for Node.js Services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  discover-and-build:
    name: Discover and Build Node.js Services
    runs-on: ubuntu-24.04

    steps:
      # Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Find services with Node.js
      - name: Discover Node.js Services
        id: discover
        working-directory: services
        run: |
          services=$(find . -name package.json -not -path "*/node_modules/*" | xargs -n1 dirname | sed 's|^\./||' | paste -sd '"","')
          echo "services=[\"$services\"]" >> $GITHUB_OUTPUT
    
    outputs:
      services: ${{ steps.discover.outputs.services }}

  build-and-test:
    name: Build and Test Node.js Services
    needs: discover-and-build
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        service: ${{ fromJson(needs.discover-and-build.outputs.services) }}

    steps:
      # Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install Dependencies
        working-directory: services/${{ matrix.service }}
        run: yarn install

      # Run tests
      - name: Run Tests
        working-directory: services/${{ matrix.service }}
        run: yarn test

      # Lint the code
      - name: Lint Code
        working-directory: services/${{ matrix.service }}
        run: yarn lint

      # Build the application
      - name: Build Application
        working-directory: services/${{ matrix.service }}
        run: yarn build

      # Generate code coverage
      - name: Generate Code Coverage
        working-directory: services/${{ matrix.service }}
        run: yarn coverage

      # Upload code coverage report
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-${{ matrix.service }}
          path: services/${{ matrix.service }}/coverage

      # Upload test results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.service }}
          path: services/${{ matrix.service }}/test-results

      # Post PR comment with build metadata
      - name: Post PR Comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const github = require('@actions/github');

            const coveragePath = path.join(process.env.GITHUB_WORKSPACE, 'services', '${{ matrix.service }}', 'coverage', 'coverage-summary.json');
            const testResultsPath = path.join(process.env.GITHUB_WORKSPACE, 'services', '${{ matrix.service }}', 'test-results', 'junit.xml');

            const buildOutput = fs.readFileSync(coveragePath, 'utf8');
            const testOutput = fs.readFileSync(testResultsPath, 'utf8');

            const commentBody = `
            ## Build and Test Results
            **Build Output:**
            \`\`\`
            ${buildOutput}
            \`\`\`
            **Test Output:**
            \`\`\`
            ${testOutput}
            \`\`\`
            `;

            const issue_number = github.context.payload.pull_request.number;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            octokit.issues.createComment({
              ...github.context.repo,
              issue_number,
              body: commentBody
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    name: Build and Push Docker Images
    needs:
      - build-and-test
      - discover-and-build
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        service: ${{ fromJson(needs.discover-and-build.outputs.services) }}

    steps:
      # Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker Image
        working-directory: services/${{ matrix.service }}
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-${{ matrix.service }}
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TAG=pr-${{ github.event.pull_request.number }}
          else
            TAG=latest
          fi
          docker build -t $IMAGE_NAME:$TAG .

      # Push Docker image
      - name: Push Docker Image
        if: github.event_name == 'push' && github.ref_name == 'main'
        working-directory: services/${{ matrix.service }}
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-${{ matrix.service }}
          TAG=latest
          docker push $IMAGE_NAME:$TAG

      # Push PR-specific Docker image
      - name: Push PR Docker Image
        if: github.event_name == 'pull_request'
        working-directory: services/${{ matrix.service }}
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-${{ matrix.service }}
          TAG=pr-${{ github.event.pull_request.number }}
          docker push $IMAGE_NAME:$TAG
